### PR TITLE
Add missing field to Information struct

### LINKED ISSUE #66: Solver info reported incorrectly?
When inspecting the `Information` object returned by the solver in order to debug the robustness for my problem, I noticed that some of the output appears to be wrong. For example, the information object claims that 72 restarts were taken (despite the fact that 3 is the maximum by default and I did not change that), only 1 jacobian evaluation was performed, and 0 minor and major iterations were performed. 

I did inspect the type definition of the `Information` struct in the `Types.h` of `pathlib` ([link](https://pages.cs.wisc.edu/~ferris/path/pathlib/include/) but couldn't find any obvious inconsistencies with the Julia definition.

Here's an example output:

```julia
PATHSolver.Information
  residual: Float64 1.3042986523364064e-8
  distance: Float64 0.0
  steplength: Float64 0.0
  total_time: Float64 1.008433
  maximum_distance: Float64 0.8244709999999807
  major_iterations: Int32 0
  mainor_iterations: Int32 0
  crash_iterations: Int32 68
  function_evaluations: Int32 19843
  jacobian_evaluations: Int32 1
  gradient_steps: Int32 485
  restarts: Int32 72
  generate_output: Int32 10
  generated_output: Int32 2
  forward: Bool false
  backtrace: Bool false
  gradient: Bool false
  use_start: Bool true
  use_basics: Bool false
  used_start: Bool false
  used_basics: Bool false
```

### PR DESCRIPTION
**Pull request by lassepe**
Resolves #66

### CODE REVIEW

**Comment by odow** [comment]
Could we add some tests for this?

**Comment by lassepe** [comment]
Kind of difficult to test I guess because we would need some C-code that produces an `Information` struct with known field values.

**Comment by lassepe** [comment]
Do you have something in mind?

**Comment by odow** [comment]
Test some of the `info` values returned here: https://github.com/chkwon/PATHSolver.jl/blob/master/test/C_API.jl

**Comment by lassepe** [comment]
I added some tests. It's a bit difficult in that we don't directly know what kind of output to expect but I added some basic sanity check to make sure that 

- the number of function evaluations is non-zero
- we don't have any restarts
- we have a residual that is consistent with the convergence criterion

These tests fail on master and work with this patch.

**Comment by odow** [comment]
Thanks! Tagging a new version now.

**Pull request merged**
