### PR TITLE
Update to support Julia >=1.3

### PR DESCRIPTION
**Pull request by jlperla**

### CODE REVIEW

**Comment by jlperla** [comment]
I think this implements #39   Or at least as far as I can test.

This package is very useful, so I hope you can test this and tag a new release.

**Comment by chkwon** [comment]
Thanks!

**Comment by jlperla** [comment]
Great. I hope I didn't make any major errors when converting to the package system. My guess is that this release is the last one needed prior to the PATH.jl binary hosting 
 It looks like you initiated a release process?

**Comment by chkwon** [comment]
No you didn't make any errors. I struggled a bit to register, but the new version is tagged and registered: `v0.6.0`. Try please and let me know. I believe PATH.jl is the future though.

**Comment by jlperla** [comment]
Updated and everything works great
I think we are all good until PATH.jl is ready

**Pull request merged**
